
steps:      
  - uses: actions/setup-node@master  

 action "Azure Login" {
  uses = "Azure/github-actions/login@master"
  env = {
    AZURE_SUBSCRIPTION = "MGM Digital Transformation (11005060)"
  }
  secrets = ["AZURE_SERVICE_APP_ID", "AZURE_SERVICE_PASSWORD", "AZURE_SERVICE_TENANT"]
}


action "Deploy to Azure  Function App" {
  uses = "Azure/github-actions/functions@master"
  needs = ["Azure Login"]
  env = {
    AZURE_APP_NAME = "GLfunction"
    AZURE_APP_PACKAGE_LOCATION = "/subscriptions/12652e5d-423a-4d65-9705-b2d088651222/resourceGroups/MGMrg/providers/Microsoft.Web/sites/GLfunction"
  }
